### ISSUE TITLE
Error: Invalid value specified for positional arg

### ISSUE THREAD

**Issue by AaronHolbrook** [runcommand/hook#9]
```
vagrant@vvv:/srv/www/test-site$ wp hook init
Error: Invalid value specified for positional arg.
```

**Comment by danielbachhuber** [comment]
Oh, sorry about that. This command is actually dependent on some WP-CLI features that haven't been released.

Can you `wp cli update --nightly` and try again?

**Comment by AaronHolbrook** [comment]
Ah, ok - cool; that did indeed fix the issue - it's now working as expected!
